on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      
      - run: npm install
      - run: npm run build
      - run: npx web-ext build
      - run: npm run changelog --silent > changelog.md
          
      - uses: softprops/action-gh-release@v2
        with:
          body_path: changelog.md
          files: web-ext-artifacts/*

